### ISSUE TITLE
ValueError: Cannot compute LDA over and empty collection 

### ISSUE THREAD

**Issue by frankchen121212** [DongqingSun96/STRIDE#5]
Hi, Thank you for the nice tool. I've been trying to run STRIDE on my own dataset. It runs successfully on 4 out of 6 datasets, but I failed to run it on the other two datasets. I've installed the environment successfully and the error is listed below.

To run STRIDE successfully, I've modified my dataset into the required txt format, I've attached the data to  [Google Drive](https://drive.google.com/drive/folders/1u0tJUsZj3bmbn3MNoywoRBLYboaW15gD?usp=sharing).

According to the data, I run:

`
STRIDE deconvolve --sc-count sc_count.txt --sc-celltype sc_celltype.txt --st-count st_count_10000.txt --outdir output/ --outprefix seqFISH+ --normalize
`

Have you encountered this error before? Hope that you can help me. Thank you!

```
(stride) chens0a@kw60968:~/STRIDE$ STRIDE deconvolve --sc-count /Dataset/ST/seqFISH+/sc_count.txt --sc-celltype /Dataset/ST/seqFISH+/sc_celltype.txt --st-count /Dataset/ST/seqFISH+/st_count_10000.txt --outdir /home/chens0a/ST-Bentchmark/STRIDE/seqFISH+/ --outprefix seqFISH+ --normalize
Reading spatial count matrix...
Reading single-cell count matrix...
Identifying markers...
Training topic model...
Selecting the optimal model.
Number of topics: 6
Traceback (most recent call last):
  File "/home/chens0a/.conda/envs/stride/bin/STRIDE", line 4, in <module>
    __import__('pkg_resources').run_script('stridespatial==0.0.2a0', 'STRIDE')
  File "/home/chens0a/.conda/envs/stride/lib/python3.8/site-packages/pkg_resources/__init__.py", line 662, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/chens0a/.conda/envs/stride/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1466, in run_script
    exec(script_code, namespace, namespace)
  File "/home/chens0a/.conda/envs/stride/lib/python3.8/site-packages/stridespatial-0.0.2a0-py3.8.egg/EGG-INFO/scripts/STRIDE", line 72, in <module>
  File "/home/chens0a/.conda/envs/stride/lib/python3.8/site-packages/stridespatial-0.0.2a0-py3.8.egg/EGG-INFO/scripts/STRIDE", line 45, in main
  File "/home/chens0a/.conda/envs/stride/lib/python3.8/site-packages/stridespatial-0.0.2a0-py3.8.egg/STRIDE/Deconvolution.py", line 257, in Deconvolve
  File "/home/chens0a/.conda/envs/stride/lib/python3.8/site-packages/stridespatial-0.0.2a0-py3.8.egg/STRIDE/ModelTrain.py", line 290, in scLDA
  File "/home/chens0a/.conda/envs/stride/lib/python3.8/site-packages/stridespatial-0.0.2a0-py3.8.egg/STRIDE/ModelTrain.py", line 211, in ModelSelect
  File "/home/chens0a/.conda/envs/stride/lib/python3.8/site-packages/stridespatial-0.0.2a0-py3.8.egg/STRIDE/ModelTrain.py", line 173, in ModelEvaluate
  File "/home/chens0a/.conda/envs/stride/lib/python3.8/site-packages/stridespatial-0.0.2a0-py3.8.egg/STRIDE/ModelTrain.py", line 104, in LDA
  File "/home/chens0a/.conda/envs/stride/lib/python3.8/site-packages/gensim/models/ldamodel.py", line 441, in __init__
    raise ValueError("cannot compute LDA over an empty collection (no terms)")
ValueError: cannot compute LDA over an empty collection (no terms)
```

**Comment by DongqingSun96** [comment]
Hi, I have checked your data. It seems that the spatial expression data `st_count_10000.txt` should be reshaped, with genes as rows and spatial spots as columns.

**Comment by frankchen121212** [comment]
Thank you, this issue is solve successfully~
