### ISSUE TITLE
IndexError: cannot do a non-empty take from an empty axes.

### ISSUE THREAD

**Issue by juliaryann** [DongqingSun96/STRIDE#7]
Hello! Thank you for making this package! I got this error and I'm not sure what it means.

 ```
STRIDE deconvolve --sc-count /home/salatti/Desktop/sc_count.csv --sc-celltype /home/salatti/Desktop/sc_meta.csv --st-count /home/salatti/Desktop/spatial_count.csv --outdir /home/salatti/Desktop --outprefix stride_deconv --normalize
Reading spatial count matrix...
Traceback (most recent call last):
  File "/home/salatti/anaconda3/envs/stride/bin/STRIDE", line 4, in <module>
    __import__('pkg_resources').run_script('stridespatial==0.0.2a0', 'STRIDE')
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/pkg_resources/__init__.py", line 662, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1466, in run_script
    exec(script_code, namespace, namespace)
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/stridespatial-0.0.2a0-py3.8.egg/EGG-INFO/scripts/STRIDE", line 72, in <module>
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/stridespatial-0.0.2a0-py3.8.egg/EGG-INFO/scripts/STRIDE", line 45, in main
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/stridespatial-0.0.2a0-py3.8.egg/STRIDE/Deconvolution.py", line 218, in Deconvolve
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/stridespatial-0.0.2a0-py3.8.egg/STRIDE/ModelTrain.py", line 94, in stProcess
  File "<__array_function__ internals>", line 180, in quantile
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4371, in quantile
    return _quantile_unchecked(
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4383, in _quantile_unchecked
    r, k = _ureduce(a,
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3702, in _ureduce
    r = func(a, **kwargs)
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4552, in _quantile_ureduce_func
    result = _quantile(arr,
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4658, in _quantile
    take(arr, indices=-1, axis=DATA_AXIS)
  File "<__array_function__ internals>", line 180, in take
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/home/salatti/anaconda3/envs/stride/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
```
Thank you for your assistance, 
Julia

**Comment by wanglabtongji** [comment]
Hi, could you please provide the input files for debugging? Thanks!
